/*
 * XPVP.PensionFunds.Customer.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package br.com.kiman.kiprev.ki.xp.integration.folheterias;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Plan {

	@XmlElement(name = "investmentFunds")
	private List<InvestmentFunds> investmentFunds = null;

	@XmlElement(name = "susepCode")
	private String susepCode = null;

	@XmlElement(name = "taxOption")
	private String taxOption = null;

	@XmlElement(name = "planType")
	private String planType = null;

	@XmlElement(name = "planName")
	private String planName = null;

	public Plan investmentFunds(List<InvestmentFunds> investmentFunds) {
		this.investmentFunds = investmentFunds;
		return this;
	}

	public Plan addInvestmentFundsItem(InvestmentFunds investmentFundsItem) {
		if (this.investmentFunds == null) {
			this.investmentFunds = new ArrayList<InvestmentFunds>();
		}
		this.investmentFunds.add(investmentFundsItem);
		return this;
	}

	public List<InvestmentFunds> getInvestmentFunds() {
		return investmentFunds;
	}

	public void setInvestmentFunds(List<InvestmentFunds> investmentFunds) {
		this.investmentFunds = investmentFunds;
	}

	public Plan susepCode(String susepCode) {
		this.susepCode = susepCode;
		return this;
	}

	public String getSusepCode() {
		return susepCode;
	}

	public void setSusepCode(String susepCode) {
		this.susepCode = susepCode;
	}

	public Plan taxOption(String taxOption) {
		this.taxOption = taxOption;
		return this;
	}

	public String getTaxOption() {
		return taxOption;
	}

	public void setTaxOption(String taxOption) {
		this.taxOption = taxOption;
	}

	public Plan planType(String planType) {
		this.planType = planType;
		return this;
	}

	public String getPlanType() {
		return planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	public Plan planName(String planName) {
		this.planName = planName;
		return this;
	}

	public String getPlanName() {
		return planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Plan plan = (Plan) o;
		return Objects.equals(this.investmentFunds, plan.investmentFunds)
				&& Objects.equals(this.susepCode, plan.susepCode) && Objects.equals(this.taxOption, plan.taxOption)
				&& Objects.equals(this.planType, plan.planType) && Objects.equals(this.planName, plan.planName);
	}

	@Override
	public int hashCode() {
		return Objects.hash(investmentFunds, susepCode, taxOption, planType, planName);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Plan {\n");

		sb.append("    investmentFunds: ").append(toIndentedString(investmentFunds)).append("\n");
		sb.append("    susepCode: ").append(toIndentedString(susepCode)).append("\n");
		sb.append("    taxOption: ").append(toIndentedString(taxOption)).append("\n");
		sb.append("    planType: ").append(toIndentedString(planType)).append("\n");
		sb.append("    planName: ").append(toIndentedString(planName)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
}
